version: '3.8'

services:
  MongoDBHotel:
    image: mongo
    container_name: MongoDBHotel
    expose:
      - '27017'
    #ports:
    #  - '27017:27017'
    restart: always

  SQLServerSecurity:
    image: mcr.microsoft.com/mssql/server
    container_name: SQLServerSecurity
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: StrongPassword1!
    expose:
      - '1433'
    #ports:
    #  - '1433:1433'
    restart: always

  hotel:
    image: hotel
    container_name: hotel
    hostname: hotel
    build:
      context: ./BackEnd/
      dockerfile: Hotel.Dockerfile
    restart: always
    expose:
      - '3000'
    #ports:
    #  - '8562:3000'
    environment:
      - APP_CONNECTION_STRING=mongodb://MongoDBHotel:27017
      - APP_DATABASE=MongoDBHotel
    depends_on:
      - MongoDBHotel
      - SQLServerSecurity

  security:
    image: security
    container_name: security
    hostname: security
    build:
      context: ./BackEnd/
      dockerfile: Security.Dockerfile
    restart: always
    expose:
      - '3000'
    #ports:
    #  - '8563:3000'
    volumes:
      - backend_photos:/app/wwwroot/photos
    environment:
      - APP_CONNECTION_STRING=Data Source=SQLServerSecurity;Initial Catalog=Security; User Id=sa;Password=StrongPassword1!;TrustServerCertificate=true;
    depends_on:
      - SQLServerSecurity
      - MongoDBHotel

  gateway:
    image: gateway
    container_name: gateway
    hostname: gateway
    build:
      context: ./BackEnd/
      dockerfile: Gateway.Dockerfile
    restart: always
    #expose:
    #  - '3000'
    ports:
      - '8562:443'
    volumes:
      - backend_photos:/app/wwwroot/photos
    depends_on:
      - hotel
      - SQLServerSecurity
      - MongoDBHotel

volumes:
  backend_photos:
