version: '3.8'

services:
  hotel:
    image: hotel
    container_name: hotel
    hostname: hotel
    build:
      context: ./
      dockerfile: Hotel.Dockerfile
    restart: always
    #expose:
    #  - '3000'
    ports:
      - '8562:3000'
    environment:
      - APP_CONNECTION_STRING=mongodb://192.168.1.226:27017
      - APP_DATABASE=MongoDBHotel
  security:
    image: security
    container_name: security
    hostname: security
    build:
      context: ./
      dockerfile: Security.Dockerfile
    restart: always
    #expose:
    #  - '3000'
    ports:
      - '8563:3000'
    environment:
      - APP_CONNECTION_STRING=Data Source=192.168.1.226; Initial Catalog=Security; User Id=sa; Password=StrongPassword1!; TrustServerCertificate=true;
  gateway:
    image: gateway
    container_name: gateway
    hostname: gateway
    build:
      context: ./
      dockerfile: Gateway.Dockerfile
    restart: always
    expose:
      - '3000'
    ports:
      - '8561:3000'
    links:
      - hotel
      - security
    depends_on:
      - hotel
      - security
